version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: Install SDK
          command:  pip3 install -r requirements.txt

      - run:
          name: Start Agent and wait for agent to register
          command: |
              set -x
              docker-compose up -d
              trap 'kill $(jobs -p)' EXIT
              attempt_counter=0
              max_attempts=45
              mkdir -p build/reports/agent
              docker-compose -f docker-compose.yml logs -f | tee build/reports/agent/log.txt&
              until curl -s http://localhost:8585/api/status | jq '.registered' | grep true; do
                if [ ${attempt_counter} -eq ${max_attempts} ]; then
                  echo "Agent failed to register. Terminating..."
                  exit 1
                fi
                attempt_counter=$(($attempt_counter+1))
                sleep 1
              done

      - run:
          name: Run Tests
          command:  pytest
